### ISSUE TITLE
Set a few topic filters

### ISSUE THREAD

**Issue by freearhey** [spencermountain/Freebase.js#17]
Can you help? How set a few topic filters in options?

**Comment by spencermountain** [comment]
hey Aleksandr, happy to help but I need a more detailed question.
Freebase is closing its API in 6 months.

**Comment by freearhey** [comment]
Hi, I mean - is it possible to add the filter list to request for receive only certain properties. For example:
freebase.topic('tom cruise', {filter: "/common/topic/description", filter: "/people/person/gender"}, function(data) {...});

About the closing Freebase API I had not know, thanks for the info. Fortunately they say it will be replaced on API Wikidata.

**Comment by spencermountain** [comment]
hey, use the search api instead of the topic api

``` javascript
freebase.search("tom cruise", {output:"(/people/person/gender description)"}, function(data){
  console.log(JSON.stringify(data, null, 2));
})
```

cheers
https://developers.google.com/freebase/v1/search-overview
