### ISSUE TITLE
Trouble installing the module

### ISSUE THREAD

**Issue by duncanmak** [spencermountain/Freebase.js#4]
I'm having trouble installing the module.

npm ERR! Error: ENOENT, chmod '/Users/duncan/git/duncanmak/MovieCastAverageAge.ts/node_modules/freebase/lib/bin'
npm ERR! If you need help, you may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com

npm ERR! System Darwin 12.2.0
npm ERR! command "/usr/local/Cellar/node/0.8.18/bin/node" "/usr/local/bin/npm" "install" "freebase"
npm ERR! cwd /Users/duncan/git/duncanmak/MovieCastAverageAge.ts
npm ERR! node -v v0.8.18
npm ERR! npm -v 1.2.2
npm ERR! path /Users/duncan/git/duncanmak/MovieCastAverageAge.ts/node_modules/freebase/lib/bin
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/duncan/git/duncanmak/MovieCastAverageAge.ts/npm-debug.log
npm ERR! not ok code 0

I googled around and it looks like some say running 'npm cache clean' should help, but I did and it didn't help.

Any suggestions?

Thanks!

Duncan.

**Comment by spencermountain** [comment]
hey duncan, looks like it's fixed now
thanks for the heads-up
cheers
