### ISSUE TITLE
Hard path to module in helpers.js

### ISSUE THREAD

**Issue by pirhoo** [spencermountain/Freebase.js#5]
Hi @spencermountain,

You forgot a hard path to your local "slow" module in helpers.js:
https://github.com/spencermountain/Freebase-nodejs/blob/master/lib/helpers.js#L2

So the last version of the module doesn't work at all.

Thanks!

**Comment by spencermountain** [comment]
Hi Pierre, thanks so much.
i've fixed it.
I'm working hard on both modules this week, so please use them with caution. I'm trying to hack them onto the clientside.
thanks!

**Comment by pirhoo** [comment]
Great ! Thanks @spencermountain !
